//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace infrastructure {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceInfra {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceInfra() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("infrastructure.ResourceInfra", typeof(ResourceInfra).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conexión invalida.
        /// </summary>
        internal static string CosmosTestConnectionError {
            get {
                return ResourceManager.GetString("CosmosTestConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to conexión exitosa.
        /// </summary>
        internal static string CosmosTestConnectionOk {
            get {
                return ResourceManager.GetString("CosmosTestConnectionOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requerimiento.
        /// </summary>
        internal static string MessageRequirement {
            get {
                return ResourceManager.GetString("MessageRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enviado con exito.
        /// </summary>
        internal static string MessageRequirementComplement {
            get {
                return ResourceManager.GetString("MessageRequirementComplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos de conexión invalidos.
        /// </summary>
        internal static string SqlTestConnectionError {
            get {
                return ResourceManager.GetString("SqlTestConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La conexión fué exitosa.
        /// </summary>
        internal static string SqlTestConnectionOk {
            get {
                return ResourceManager.GetString("SqlTestConnectionOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MongoLocal.
        /// </summary>
        internal static string TypeConnectionCosmos {
            get {
                return ResourceManager.GetString("TypeConnectionCosmos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SqlServerSP.
        /// </summary>
        internal static string TypeConnectionSql {
            get {
                return ResourceManager.GetString("TypeConnectionSql", resourceCulture);
            }
        }
    }
}
